### ISSUE TITLE
Add cool animation on buttons

### ISSUE THREAD

**Issue by stupid-kid-af** [stupid-kid-af/Gradient-Generator-Javascript#6]

**Comment by Aagam-Jain-113** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by Aagam-Jain-113** [comment]
Do you want me to add animations on arrow buttons or generate button @stupid-kid-af?

**Comment by stupid-kid-af** [comment]
Yes

**Comment by Aagam-Jain-113** [comment]
I have added the animations and PR has been made. If you like it accept it and add hactober-accepted label?

**Comment by stupid-kid-af** [comment]
Thanks to @Aagam-Jain-113 @pdejan for fixing this issue.
